package com.djavafactory.pttech.rrm.web;

import java.util.List;

import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

import com.djavafactory.pttech.rrm.domain.Configuration;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.util.StringUtils;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;


/**
 * This class is generated by <b>jasperoo setup</b>.
 * Request mapping methods are added by <b>jasperoo add</b> or <b>jasperoo all</b>.
 * <p/>
 * <b>ANYTHING ADDED AFTER THE CLOSING BRACE WILL BE DELETED BY <u>jasperoo add</u>!</b>
 */
@RequestMapping("/reports")
@Controller
public class ReportController {

    public static final String REPORT_TYPE_CELCOM = "celcom";
    public static final String REPORT_TYPE_TNG = "tng";

    @RequestMapping(method = RequestMethod.GET)
    public String getReportList(@RequestParam(value = "type") String type, Model uiModel) {
        List<Configuration> configList = Configuration.findByConfigKeyPrefix(type);
        if (configList != null && !configList.isEmpty()) {
            for (int i = 0; i < configList.size(); i++) {
                Configuration config = configList.get(i);
                if (config.getConfigKey().lastIndexOf(".") > -1) {
                    config.setConfigKey(config.getConfigKey().substring(config.getConfigKey().lastIndexOf(".") + 1));
                }
            }
        }
        uiModel.addAttribute("reports", configList);
        return "reports/reportList";
    }

/*
* The template for the "List" Request mapping methods is:
*
*	@RequestMapping(value ="/**ENTITY_NAME_LOWER**List/{format}", method = RequestMethod.GET)
*	public String report**ENTITY_NAME**List(ModelMap modelMap, @PathVariable("format") String format) {
*		JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(**ENTITY_NAME**.findAll**REPORT_TITLE**(),false);
*		modelMap.put("reportData", jrDataSource);
*		modelMap.put("format", format);
*		return "**ENTITY_NAME_LOWER**ReportList";
*	}
*/

    @RequestMapping(value = "/reloadrequestList/{format}", method = RequestMethod.GET)
    public String reportReloadRequestList(ModelMap modelMap, @PathVariable("format") String format) {
        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "reloadrequestReportList";
    }

//	@RequestMapping(value ="/reloadrequestDetail/{id}/{format}", method = RequestMethod.GET)
//	public String reportReloadRequestDetail(ModelMap modelMap, @PathVariable("id") Long id, @PathVariable("format") String format) {
//		JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findReloadRequestsById(id).getResultList(),false);
//		modelMap.put("reportData", jrDataSource);
//		modelMap.put("format", format);
//		return "reloadrequestReportDetail";
//	}

    /*
      * TnG Report
      */
    @RequestMapping(value = "/dailyDetailsRequestReloadFrmCelcomReport/{format}", method = RequestMethod.GET)
    public String dailyDetailsRequestReloadFfmCelcomReport(ModelMap modelMap,
                                                           @PathVariable("format") String format) {

        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "dailyDetailsRequestReloadFrmCelcomReport";
    }

    @RequestMapping(value = "/summaryRequestReloadFrmCelcomReport/{format}", method = RequestMethod.GET)
    public String summaryRequestReloadFrmCelcomReport(ModelMap modelMap,
                                                      @PathVariable("format") String format) {

        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "summaryRequestReloadFrmCelcomReport";
    }

    @RequestMapping(value = "/dailyDetailedReloadFrmCelcomReport/{format}", method = RequestMethod.GET)
    public String dailyDetailedReloadFrmCelcomReport(ModelMap modelMap,
                                                     @PathVariable("format") String format) {

        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "dailyDetailedReloadFrmCelcomReport";
    }

    @RequestMapping(value = "/summaryReloadFrmCelcomReport/{format}", method = RequestMethod.GET)
    public String summaryReloadFrmCelcomReport(ModelMap modelMap,
                                               @PathVariable("format") String format) {

        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "summaryReloadFrmCelcomReport";
    }

    @RequestMapping(value = "/dailyDetailsCancellationReloadReqFrmCelcomReport/{format}", method = RequestMethod.GET)
    public String dailyDetailsCancellationReloadReqFrmCelcomReport(ModelMap modelMap,
                                                                   @PathVariable("format") String format) {

        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "dailyDetailsCancellationReloadReqFrmCelcomReport";
    }

    @RequestMapping(value = "/summaryCancellationReloadFrmCelcomReport/{format}", method = RequestMethod.GET)
    public String summaryCancellationReloadFrmCelcomReport(ModelMap modelMap,
                                                           @PathVariable("format") String format) {

        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "summaryCancellationReloadFrmCelcomReport";
    }

    @RequestMapping(value = "/dailySettlementReloadFrmCelcomReport/{format}", method = RequestMethod.GET)
    public String dailySettlementReloadFrmCelcomReport(ModelMap modelMap,
                                                       @PathVariable("format") String format) {

        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "dailySettlementReloadFrmCelcomReport";
    }

    @RequestMapping(value = "/monthlySettlementReloadFrmCelcomReport/{format}", method = RequestMethod.GET)
    public String monthlySettlementReloadFrmCelcomReport(ModelMap modelMap,
                                                         @PathVariable("format") String format) {

        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "monthlySettlementReloadFrmCelcomReport";
    }

    @RequestMapping(value = "/dailyTrxDetailsReport/{format}", method = RequestMethod.GET)
    public String dailyTrxDetailsReport(ModelMap modelMap,
                                        @PathVariable("format") String format) {

        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "dailyTrxDetailsReport";
    }

    @RequestMapping(value = "/dailyTrxDetailsByRangeDateReport/{format}", method = RequestMethod.GET)
    public String dailyTrxDetailsByRangeDateReport(ModelMap modelMap,
                                                   @PathVariable("format") String format,
                                                   @RequestParam("startDate") String startDate,
                                                   @RequestParam("endDate") String endDate) {

        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "dailyTrxDetailsByRangeDateReport";
    }

    @RequestMapping(value = "/dailyTrxFeeDetailsReport/{format}", method = RequestMethod.GET)
    public String dailyTrxFeeDetailsReport(ModelMap modelMap,
                                           @PathVariable("format") String format) {

        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "dailyTrxFeeDetailsReport";
    }

    @RequestMapping(value = "/dailyTrxFeeDetailsByRangeDateReport/{format}", method = RequestMethod.GET)
    public String dailyTrxFeeDetailsByRangeDateReport(ModelMap modelMap,
                                                      @PathVariable("format") String format,
                                                      @RequestParam("startDate") String startDate,
                                                      @RequestParam("endDate") String endDate) {

        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "dailyTrxFeeDetailsByRangeDateReport";
    }

    @RequestMapping(value = "/summaryDailyTrxReport/{format}", method = RequestMethod.GET)
    public String summaryDailyTrxReport(ModelMap modelMap,
                                        @PathVariable("format") String format) {

        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "summaryDailyTrxReport";
    }

    @RequestMapping(value = "/summaryDailyTrxByRangeDateReport/{format}", method = RequestMethod.GET)
    public String summaryDailyTrxByRangeDateReport(ModelMap modelMap,
                                                   @PathVariable("format") String format,
                                                   @RequestParam("startDate") String startDate,
                                                   @RequestParam("endDate") String endDate) {

        JRBeanCollectionDataSource jrDataSource = new JRBeanCollectionDataSource(com.djavafactory.pttech.rrm.domain.ReloadRequest.findAllReloadRequests(), false);
        modelMap.put("reportData", jrDataSource);
        modelMap.put("format", format);
        return "summaryDailyTrxByRangeDateReport";
    }


}
