// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.djavafactory.pttech.rrm.client.managed.request;

import com.djavafactory.pttech.rrm.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory {

    TerminalRequest terminalRequest();

    ReloadRequestRequest reloadRequestRequest();

    ParamRequest paramRequest();

    FirmwareRequest firmwareRequest();

    ConfigurationRequest configurationRequest();
}
