// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.djavafactory.pttech.rrm.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("com.djavafactory.pttech.rrm.domain.Configuration")
@ServiceName("com.djavafactory.pttech.rrm.domain.Configuration")
public interface ConfigurationRequest extends RequestContext {

    abstract Request<java.lang.Long> countConfigurations();

    abstract Request<java.util.List<com.djavafactory.pttech.rrm.client.managed.request.ConfigurationProxy>> findAllConfigurations();

    abstract Request<java.util.List<com.djavafactory.pttech.rrm.client.managed.request.ConfigurationProxy>> findConfigurationEntries(int firstResult, int maxResults);

    abstract Request<com.djavafactory.pttech.rrm.client.managed.request.ConfigurationProxy> findConfiguration(Long id);

    abstract InstanceRequest<com.djavafactory.pttech.rrm.client.managed.request.ConfigurationProxy, java.lang.Void> remove();

    abstract InstanceRequest<com.djavafactory.pttech.rrm.client.managed.request.ConfigurationProxy, java.lang.Void> persist();
}
