// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.djavafactory.pttech.rrm.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import java.util.Date;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("com.djavafactory.pttech.rrm.domain.Firmware")
@ProxyForName("com.djavafactory.pttech.rrm.domain.Firmware")
public interface FirmwareProxy extends EntityProxy {

    abstract Long getId();

    abstract Integer getVersion();

    abstract String getTerminalId();

    abstract String getFirmwareFile();

    abstract String getStatus();

    abstract String getCreatedBy();

    abstract Date getCreatedTime();

    abstract void setId(Long id);

    abstract void setVersion(Integer version);

    abstract void setTerminalId(String terminalId);

    abstract void setFirmwareFile(String firmwareFile);

    abstract void setStatus(String status);

    abstract void setCreatedBy(String createdBy);

    abstract void setCreatedTime(Date createdTime);
}
