// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.djavafactory.pttech.rrm.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("com.djavafactory.pttech.rrm.domain.Param")
@ServiceName("com.djavafactory.pttech.rrm.domain.Param")
public interface ParamRequest extends RequestContext {

    abstract Request<java.lang.Long> countParams();

    abstract Request<java.util.List<com.djavafactory.pttech.rrm.client.managed.request.ParamProxy>> findAllParams();

    abstract Request<java.util.List<com.djavafactory.pttech.rrm.client.managed.request.ParamProxy>> findParamEntries(int firstResult, int maxResults);

    abstract Request<com.djavafactory.pttech.rrm.client.managed.request.ParamProxy> findParam(Long id);

    abstract InstanceRequest<com.djavafactory.pttech.rrm.client.managed.request.ParamProxy, java.lang.Void> remove();

    abstract InstanceRequest<com.djavafactory.pttech.rrm.client.managed.request.ParamProxy, java.lang.Void> persist();
}
