// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.djavafactory.pttech.rrm.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("com.djavafactory.pttech.rrm.domain.ReloadRequest")
@ServiceName("com.djavafactory.pttech.rrm.domain.ReloadRequest")
public interface ReloadRequestRequest extends RequestContext {

    abstract Request<java.lang.Long> countReloadRequests();

    abstract Request<java.util.List<com.djavafactory.pttech.rrm.client.managed.request.ReloadRequestProxy>> findAllReloadRequests();

    abstract Request<java.util.List<com.djavafactory.pttech.rrm.client.managed.request.ReloadRequestProxy>> findReloadRequestEntries(int firstResult, int maxResults);

    abstract Request<com.djavafactory.pttech.rrm.client.managed.request.ReloadRequestProxy> findReloadRequest(Long id);

    abstract InstanceRequest<com.djavafactory.pttech.rrm.client.managed.request.ReloadRequestProxy, java.lang.Void> remove();

    abstract InstanceRequest<com.djavafactory.pttech.rrm.client.managed.request.ReloadRequestProxy, java.lang.Void> persist();
}
