// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.djavafactory.pttech.rrm.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import java.util.Date;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("com.djavafactory.pttech.rrm.domain.Terminal")
@ProxyForName("com.djavafactory.pttech.rrm.domain.Terminal")
public interface TerminalProxy extends EntityProxy {

    abstract Long getId();

    abstract Integer getVersion();

    abstract String getName();

    abstract String getLocation();

    abstract String getStatus();

    abstract Date getCreatedTime();

    abstract Date getModifiedTime();

    abstract String getCreatedBy();

    abstract String getModifiedBy();

    abstract void setId(Long id);

    abstract void setVersion(Integer version);

    abstract void setName(String name);

    abstract void setLocation(String location);

    abstract void setStatus(String status);

    abstract void setCreatedTime(Date createdTime);

    abstract void setModifiedTime(Date modifiedTime);

    abstract void setCreatedBy(String createdBy);

    abstract void setModifiedBy(String modifiedBy);
}
