// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.djavafactory.pttech.rrm.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("com.djavafactory.pttech.rrm.domain.Terminal")
@ServiceName("com.djavafactory.pttech.rrm.domain.Terminal")
public interface TerminalRequest extends RequestContext {

    abstract Request<java.lang.Long> countTerminals();

    abstract Request<java.util.List<com.djavafactory.pttech.rrm.client.managed.request.TerminalProxy>> findAllTerminals();

    abstract Request<java.util.List<com.djavafactory.pttech.rrm.client.managed.request.TerminalProxy>> findTerminalEntries(int firstResult, int maxResults);

    abstract Request<com.djavafactory.pttech.rrm.client.managed.request.TerminalProxy> findTerminal(Long id);

    abstract InstanceRequest<com.djavafactory.pttech.rrm.client.managed.request.TerminalProxy, java.lang.Void> remove();

    abstract InstanceRequest<com.djavafactory.pttech.rrm.client.managed.request.TerminalProxy, java.lang.Void> persist();
}
