// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.djavafactory.pttech.rrm.client.managed.activity;

import com.djavafactory.pttech.rrm.client.managed.request.ApplicationEntityTypesProcessor;
import com.djavafactory.pttech.rrm.client.managed.request.ApplicationRequestFactory;
import com.djavafactory.pttech.rrm.client.managed.request.ConfigurationProxy;
import com.djavafactory.pttech.rrm.client.managed.request.FirmwareProxy;
import com.djavafactory.pttech.rrm.client.managed.request.ParamProxy;
import com.djavafactory.pttech.rrm.client.managed.request.ReloadRequestProxy;
import com.djavafactory.pttech.rrm.client.managed.request.TerminalProxy;
import com.djavafactory.pttech.rrm.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;

public abstract class ApplicationDetailsActivities_Roo_Gwt implements ActivityMapper {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    public Activity getActivity(Place place) {
        if (!(place instanceof ProxyPlace)) {
            return null;
        }
        final ProxyPlace proxyPlace = (ProxyPlace) place;
        return new ApplicationEntityTypesProcessor<Activity>() {

            @Override
            public void handleTerminal(TerminalProxy proxy) {
                setResult(new TerminalActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }

            @Override
            public void handleReloadRequest(ReloadRequestProxy proxy) {
                setResult(new ReloadRequestActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }

            @Override
            public void handleParam(ParamProxy proxy) {
                setResult(new ParamActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }

            @Override
            public void handleFirmware(FirmwareProxy proxy) {
                setResult(new FirmwareActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }

            @Override
            public void handleConfiguration(ConfigurationProxy proxy) {
                setResult(new ConfigurationActivitiesMapper(requests, placeController).getActivity(proxyPlace));
            }
        }.process(proxyPlace.getProxyClass());
    }
}
