// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.djavafactory.pttech.rrm.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AcquirerIntegrationTest_Roo_IntegrationTest {

    declare @type: AcquirerIntegrationTest:@RunWith(SpringJUnit4ClassRunner.class);

    declare @type: AcquirerIntegrationTest:@ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");

    declare @type: AcquirerIntegrationTest:@Transactional;

    @Test
    public void AcquirerIntegrationTest.testCountAcquirers() {
        org.junit.Assert.assertNotNull("Data on demand for 'Acquirer' failed to initialize correctly", dod.getRandomAcquirer());
        long count = com.djavafactory.pttech.rrm.domain.Acquirer.countAcquirers();
        org.junit.Assert.assertTrue("Counter for 'Acquirer' incorrectly reported there were no entries", count > 0);
    }

    @Test
    public void AcquirerIntegrationTest.testFindAcquirer() {
        com.djavafactory.pttech.rrm.domain.Acquirer obj = dod.getRandomAcquirer();
        org.junit.Assert.assertNotNull("Data on demand for 'Acquirer' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Acquirer' failed to provide an identifier", id);
        obj = com.djavafactory.pttech.rrm.domain.Acquirer.findAcquirer(id);
        org.junit.Assert.assertNotNull("Find method for 'Acquirer' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Acquirer' returned the incorrect identifier", id, obj.getId());
    }

    @Test
    public void AcquirerIntegrationTest.testFindAllAcquirers() {
        org.junit.Assert.assertNotNull("Data on demand for 'Acquirer' failed to initialize correctly", dod.getRandomAcquirer());
        long count = com.djavafactory.pttech.rrm.domain.Acquirer.countAcquirers();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Acquirer', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.djavafactory.pttech.rrm.domain.Acquirer> result = com.djavafactory.pttech.rrm.domain.Acquirer.findAllAcquirers();
        org.junit.Assert.assertNotNull("Find all method for 'Acquirer' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Acquirer' failed to return any data", result.size() > 0);
    }

    @Test
    public void AcquirerIntegrationTest.testFindAcquirerEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Acquirer' failed to initialize correctly", dod.getRandomAcquirer());
        long count = com.djavafactory.pttech.rrm.domain.Acquirer.countAcquirers();
        if (count > 20) count = 20;
        java.util.List<com.djavafactory.pttech.rrm.domain.Acquirer> result = com.djavafactory.pttech.rrm.domain.Acquirer.findAcquirerEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Acquirer' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Acquirer' returned an incorrect number of entries", count, result.size());
    }

    @Test
    public void AcquirerIntegrationTest.testFlush() {
        com.djavafactory.pttech.rrm.domain.Acquirer obj = dod.getRandomAcquirer();
        org.junit.Assert.assertNotNull("Data on demand for 'Acquirer' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Acquirer' failed to provide an identifier", id);
        obj = com.djavafactory.pttech.rrm.domain.Acquirer.findAcquirer(id);
        org.junit.Assert.assertNotNull("Find method for 'Acquirer' illegally returned null for id '" + id + "'", obj);
        boolean modified = dod.modifyAcquirer(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Acquirer' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }

    @Test
    public void AcquirerIntegrationTest.testMerge() {
        com.djavafactory.pttech.rrm.domain.Acquirer obj = dod.getRandomAcquirer();
        org.junit.Assert.assertNotNull("Data on demand for 'Acquirer' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Acquirer' failed to provide an identifier", id);
        obj = com.djavafactory.pttech.rrm.domain.Acquirer.findAcquirer(id);
        boolean modified = dod.modifyAcquirer(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.djavafactory.pttech.rrm.domain.Acquirer merged = (com.djavafactory.pttech.rrm.domain.Acquirer) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Acquirer' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }

    @Test
    public void AcquirerIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Acquirer' failed to initialize correctly", dod.getRandomAcquirer());
        com.djavafactory.pttech.rrm.domain.Acquirer obj = dod.getNewTransientAcquirer(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Acquirer' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Acquirer' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Acquirer' identifier to no longer be null", obj.getId());
    }

    @Test
    public void AcquirerIntegrationTest.testRemove() {
        com.djavafactory.pttech.rrm.domain.Acquirer obj = dod.getRandomAcquirer();
        org.junit.Assert.assertNotNull("Data on demand for 'Acquirer' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Acquirer' failed to provide an identifier", id);
        obj = com.djavafactory.pttech.rrm.domain.Acquirer.findAcquirer(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Acquirer' with identifier '" + id + "'", com.djavafactory.pttech.rrm.domain.Acquirer.findAcquirer(id));
    }

}
