// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.djavafactory.pttech.rrm.domain;

import com.djavafactory.pttech.rrm.domain.ConfigurationDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConfigurationIntegrationTest_Roo_IntegrationTest {

    declare @type: ConfigurationIntegrationTest:@RunWith(SpringJUnit4ClassRunner.class);

    declare @type: ConfigurationIntegrationTest:@Transactional;

    @Autowired
    private ConfigurationDataOnDemand ConfigurationIntegrationTest.dod;

    @Test
    public void ConfigurationIntegrationTest.testCountConfigurations() {
        org.junit.Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", dod.getRandomConfiguration());
        long count = com.djavafactory.pttech.rrm.domain.Configuration.countConfigurations();
        org.junit.Assert.assertTrue("Counter for 'Configuration' incorrectly reported there were no entries", count > 0);
    }

    @Test
    public void ConfigurationIntegrationTest.testFindConfiguration() {
        com.djavafactory.pttech.rrm.domain.Configuration obj = dod.getRandomConfiguration();
        org.junit.Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Configuration' failed to provide an identifier", id);
        obj = com.djavafactory.pttech.rrm.domain.Configuration.findConfiguration(id);
        org.junit.Assert.assertNotNull("Find method for 'Configuration' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Configuration' returned the incorrect identifier", id, obj.getId());
    }

    @Test
    public void ConfigurationIntegrationTest.testFindAllConfigurations() {
        org.junit.Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", dod.getRandomConfiguration());
        long count = com.djavafactory.pttech.rrm.domain.Configuration.countConfigurations();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Configuration', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.djavafactory.pttech.rrm.domain.Configuration> result = com.djavafactory.pttech.rrm.domain.Configuration.findAllConfigurations();
        org.junit.Assert.assertNotNull("Find all method for 'Configuration' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Configuration' failed to return any data", result.size() > 0);
    }

    @Test
    public void ConfigurationIntegrationTest.testFindConfigurationEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", dod.getRandomConfiguration());
        long count = com.djavafactory.pttech.rrm.domain.Configuration.countConfigurations();
        if (count > 20) count = 20;
        java.util.List<com.djavafactory.pttech.rrm.domain.Configuration> result = com.djavafactory.pttech.rrm.domain.Configuration.findConfigurationEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Configuration' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Configuration' returned an incorrect number of entries", count, result.size());
    }

    @Test
    public void ConfigurationIntegrationTest.testFlush() {
        com.djavafactory.pttech.rrm.domain.Configuration obj = dod.getRandomConfiguration();
        org.junit.Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Configuration' failed to provide an identifier", id);
        obj = com.djavafactory.pttech.rrm.domain.Configuration.findConfiguration(id);
        org.junit.Assert.assertNotNull("Find method for 'Configuration' illegally returned null for id '" + id + "'", obj);
        boolean modified = dod.modifyConfiguration(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Configuration' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }

    @Test
    public void ConfigurationIntegrationTest.testMerge() {
        com.djavafactory.pttech.rrm.domain.Configuration obj = dod.getRandomConfiguration();
        org.junit.Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Configuration' failed to provide an identifier", id);
        obj = com.djavafactory.pttech.rrm.domain.Configuration.findConfiguration(id);
        boolean modified = dod.modifyConfiguration(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.djavafactory.pttech.rrm.domain.Configuration merged = (com.djavafactory.pttech.rrm.domain.Configuration) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Configuration' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }

    @Test
    public void ConfigurationIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", dod.getRandomConfiguration());
        com.djavafactory.pttech.rrm.domain.Configuration obj = dod.getNewTransientConfiguration(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Configuration' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Configuration' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Configuration' identifier to no longer be null", obj.getId());
    }

    @Test
    public void ConfigurationIntegrationTest.testRemove() {
        com.djavafactory.pttech.rrm.domain.Configuration obj = dod.getRandomConfiguration();
        org.junit.Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Configuration' failed to provide an identifier", id);
        obj = com.djavafactory.pttech.rrm.domain.Configuration.findConfiguration(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Configuration' with identifier '" + id + "'", com.djavafactory.pttech.rrm.domain.Configuration.findConfiguration(id));
    }

}
