// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.djavafactory.pttech.rrm.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FirmwareIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FirmwareIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FirmwareIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FirmwareIntegrationTest: @Transactional;
    
    @Test
    public void FirmwareIntegrationTest.testCountFirmwares() {
        org.junit.Assert.assertNotNull("Data on demand for 'Firmware' failed to initialize correctly", dod.getRandomFirmware());
        long count = com.djavafactory.pttech.rrm.domain.Firmware.countFirmwares();
        org.junit.Assert.assertTrue("Counter for 'Firmware' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FirmwareIntegrationTest.testFindFirmware() {
        com.djavafactory.pttech.rrm.domain.Firmware obj = dod.getRandomFirmware();
        org.junit.Assert.assertNotNull("Data on demand for 'Firmware' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Firmware' failed to provide an identifier", id);
        obj = com.djavafactory.pttech.rrm.domain.Firmware.findFirmware(id);
        org.junit.Assert.assertNotNull("Find method for 'Firmware' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Firmware' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FirmwareIntegrationTest.testFindAllFirmwares() {
        org.junit.Assert.assertNotNull("Data on demand for 'Firmware' failed to initialize correctly", dod.getRandomFirmware());
        long count = com.djavafactory.pttech.rrm.domain.Firmware.countFirmwares();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Firmware', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.djavafactory.pttech.rrm.domain.Firmware> result = com.djavafactory.pttech.rrm.domain.Firmware.findAllFirmwares();
        org.junit.Assert.assertNotNull("Find all method for 'Firmware' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Firmware' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FirmwareIntegrationTest.testFindFirmwareEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Firmware' failed to initialize correctly", dod.getRandomFirmware());
        long count = com.djavafactory.pttech.rrm.domain.Firmware.countFirmwares();
        if (count > 20) count = 20;
        java.util.List<com.djavafactory.pttech.rrm.domain.Firmware> result = com.djavafactory.pttech.rrm.domain.Firmware.findFirmwareEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Firmware' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Firmware' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FirmwareIntegrationTest.testFlush() {
        com.djavafactory.pttech.rrm.domain.Firmware obj = dod.getRandomFirmware();
        org.junit.Assert.assertNotNull("Data on demand for 'Firmware' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Firmware' failed to provide an identifier", id);
        obj = com.djavafactory.pttech.rrm.domain.Firmware.findFirmware(id);
        org.junit.Assert.assertNotNull("Find method for 'Firmware' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFirmware(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Firmware' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FirmwareIntegrationTest.testMerge() {
        com.djavafactory.pttech.rrm.domain.Firmware obj = dod.getRandomFirmware();
        org.junit.Assert.assertNotNull("Data on demand for 'Firmware' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Firmware' failed to provide an identifier", id);
        obj = com.djavafactory.pttech.rrm.domain.Firmware.findFirmware(id);
        boolean modified =  dod.modifyFirmware(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.djavafactory.pttech.rrm.domain.Firmware merged = (com.djavafactory.pttech.rrm.domain.Firmware) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Firmware' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FirmwareIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Firmware' failed to initialize correctly", dod.getRandomFirmware());
        com.djavafactory.pttech.rrm.domain.Firmware obj = dod.getNewTransientFirmware(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Firmware' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Firmware' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Firmware' identifier to no longer be null", obj.getId());
    }
    
}
