// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.djavafactory.pttech.rrm.domain;

import com.djavafactory.pttech.rrm.domain.Param;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect ParamDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ParamDataOnDemand: @Component;
    
    private Random ParamDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Param> ParamDataOnDemand.data;
    
    public Param ParamDataOnDemand.getNewTransientParam(int index) {
        com.djavafactory.pttech.rrm.domain.Param obj = new com.djavafactory.pttech.rrm.domain.Param();
        setParameterFile(obj, index);
        setCreatedBy(obj, index);
        setCreatedTime(obj, index);
        return obj;
    }
    
    public void ParamDataOnDemand.setParameterFile(Param obj, int index) {
        byte[] parameterFile = String.valueOf(index).getBytes();
        obj.setParameterFile(parameterFile);
    }
    
    public void ParamDataOnDemand.setCreatedBy(Param obj, int index) {
        java.lang.String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void ParamDataOnDemand.setCreatedTime(Param obj, int index) {
        java.util.Date createdTime = new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedTime(createdTime);
    }
    
    public Param ParamDataOnDemand.getSpecificParam(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Param obj = data.get(index);
        return Param.findParam(obj.getId());
    }
    
    public Param ParamDataOnDemand.getRandomParam() {
        init();
        Param obj = data.get(rnd.nextInt(data.size()));
        return Param.findParam(obj.getId());
    }
    
    public boolean ParamDataOnDemand.modifyParam(Param obj) {
        return false;
    }
    
    public void ParamDataOnDemand.init() {
        data = com.djavafactory.pttech.rrm.domain.Param.findParamEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Param' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.djavafactory.pttech.rrm.domain.Param>();
        for (int i = 0; i < 10; i++) {
            com.djavafactory.pttech.rrm.domain.Param obj = getNewTransientParam(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
