// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.djavafactory.pttech.rrm.client.managed.ui;

import com.djavafactory.pttech.rrm.client.managed.request.ConfigurationProxy;
import com.djavafactory.pttech.rrm.client.scaffold.place.ProxyDetailsView;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;

public abstract class ConfigurationMobileDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<ConfigurationProxy> {

    @UiField
    Element id;

    @UiField
    Element version;

    @UiField
    Element configKey;

    @UiField
    Element configValue;

    @UiField
    Element ordering;

    ConfigurationProxy proxy;

    public void setValue(ConfigurationProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        configKey.setInnerText(proxy.getConfigKey() == null ? "" : String.valueOf(proxy.getConfigKey()));
        configValue.setInnerText(proxy.getConfigValue() == null ? "" : String.valueOf(proxy.getConfigValue()));
        ordering.setInnerText(proxy.getOrdering() == null ? "" : String.valueOf(proxy.getOrdering()));
    }
}
