// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.djavafactory.pttech.rrm.client.managed.ui;

import com.djavafactory.pttech.rrm.client.managed.request.FirmwareProxy;
import com.djavafactory.pttech.rrm.client.scaffold.place.ProxyDetailsView;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;

public abstract class FirmwareMobileDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<FirmwareProxy> {

    @UiField
    Element id;

    @UiField
    Element version;

    @UiField
    Element terminalId;

    @UiField
    Element firmwareFile;

    @UiField
    Element status;

    @UiField
    Element createdBy;

    @UiField
    Element createdTime;

    FirmwareProxy proxy;

    public void setValue(FirmwareProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        terminalId.setInnerText(proxy.getTerminalId() == null ? "" : String.valueOf(proxy.getTerminalId()));
        firmwareFile.setInnerText(proxy.getFirmwareFile() == null ? "" : String.valueOf(proxy.getFirmwareFile()));
        status.setInnerText(proxy.getStatus() == null ? "" : String.valueOf(proxy.getStatus()));
        createdBy.setInnerText(proxy.getCreatedBy() == null ? "" : String.valueOf(proxy.getCreatedBy()));
        createdTime.setInnerText(proxy.getCreatedTime() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getCreatedTime()));
    }
}
