// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.djavafactory.pttech.rrm.client.managed.ui;

import com.djavafactory.pttech.rrm.client.managed.request.ParamProxy;
import com.djavafactory.pttech.rrm.client.scaffold.place.ProxyDetailsView;
import com.djavafactory.pttech.rrm.client.scaffold.place.ProxyListView;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;

public abstract class ParamDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<ParamProxy> {

    @UiField
    SpanElement id;

    @UiField
    SpanElement version;

    @UiField
    SpanElement terminalId;

    @UiField
    SpanElement parameterFile;

    @UiField
    SpanElement status;

    @UiField
    SpanElement createdBy;

    @UiField
    SpanElement createdTime;

    ParamProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(ParamProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        terminalId.setInnerText(proxy.getTerminalId() == null ? "" : String.valueOf(proxy.getTerminalId()));
        parameterFile.setInnerText(proxy.getParameterFile() == null ? "" : String.valueOf(proxy.getParameterFile()));
        status.setInnerText(proxy.getStatus() == null ? "" : String.valueOf(proxy.getStatus()));
        createdBy.setInnerText(proxy.getCreatedBy() == null ? "" : String.valueOf(proxy.getCreatedBy()));
        createdTime.setInnerText(proxy.getCreatedTime() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getCreatedTime()));
        displayRenderer.setInnerText(com.djavafactory.pttech.rrm.client.managed.ui.ParamProxyRenderer.instance().render(proxy));
    }
}
