// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.djavafactory.pttech.rrm.client.managed.ui;

import com.djavafactory.pttech.rrm.client.managed.request.ReloadRequestProxy;
import com.djavafactory.pttech.rrm.client.scaffold.place.ProxyDetailsView;
import com.djavafactory.pttech.rrm.client.scaffold.place.ProxyListView;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;

public abstract class ReloadRequestDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<ReloadRequestProxy> {

    @UiField
    SpanElement id;

    @UiField
    SpanElement version;

    @UiField
    SpanElement transId;

    @UiField
    SpanElement status;

    @UiField
    SpanElement mfgNumber;

    @UiField
    SpanElement reloadAmount;

    @UiField
    SpanElement serviceProviderId;

    @UiField
    SpanElement transCode;

    @UiField
    SpanElement requestedTime;

    @UiField
    SpanElement tngKey;

    ReloadRequestProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(ReloadRequestProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        transId.setInnerText(proxy.getTransId() == null ? "" : String.valueOf(proxy.getTransId()));
        status.setInnerText(proxy.getStatus() == null ? "" : String.valueOf(proxy.getStatus()));
        mfgNumber.setInnerText(proxy.getMfgNumber() == null ? "" : String.valueOf(proxy.getMfgNumber()));
        reloadAmount.setInnerText(proxy.getReloadAmount() == null ? "" : String.valueOf(proxy.getReloadAmount()));
        serviceProviderId.setInnerText(proxy.getServiceProviderId() == null ? "" : String.valueOf(proxy.getServiceProviderId()));
        transCode.setInnerText(proxy.getTransCode() == null ? "" : String.valueOf(proxy.getTransCode()));
        requestedTime.setInnerText(proxy.getRequestedTime() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getRequestedTime()));
        tngKey.setInnerText(proxy.getTngKey() == null ? "" : String.valueOf(proxy.getTngKey()));
        displayRenderer.setInnerText(com.djavafactory.pttech.rrm.client.managed.ui.ReloadRequestProxyRenderer.instance().render(proxy));
    }
}
